version: "3.9"
services:
  db:
    image: postgres:13.4
    restart: always
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
  flask:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: pipenv run flask run --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/app/:delegated
    ports:
      - 8080:8080
    depends_on:
      - db

  deamon:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: pipenv run python update_prices.py
    volumes:
      - ./:/usr/src/app/:delegated
    depends_on:
      - db